POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "vicky_vicky",
  "password": "viki_123",
  "name": "viki",
  "gender": "male"
}

###
POST  http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}


###
GET http://localhost:3000/user/tweets/feed/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MDI0NTI4fQ.fud-xwbiVHRZby2wJxNNWuPVataoZSyZaMaZKKs7PbA

###
GET http://localhost:3000/user/following/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MDI0NTI4fQ.fud-xwbiVHRZby2wJxNNWuPVataoZSyZaMaZKKs7PbA

### 
DELETE http://localhost:3000/tweets/27/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MDI0NTI4fQ.fud-xwbiVHRZby2wJxNNWuPVataoZSyZaMaZKKs7PbA

####
POST http://localhost:3000/user/tweets/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MDI0NTI4fQ.fud-xwbiVHRZby2wJxNNWuPVataoZSyZaMaZKKs7PbA

{
   "tweet": "The Evening..."
}

###
GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MDI0NTI4fQ.fud-xwbiVHRZby2wJxNNWuPVataoZSyZaMaZKKs7PbA

### 
GET http://localhost:3000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MDI0NTI4fQ.fud-xwbiVHRZby2wJxNNWuPVataoZSyZaMaZKKs7PbA

###
GET http://localhost:3000/tweets/6/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MDI0NTI4fQ.fud-xwbiVHRZby2wJxNNWuPVataoZSyZaMaZKKs7PbA

###
GET http://localhost:3000/tweets/9/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MDI0NTI4fQ.fud-xwbiVHRZby2wJxNNWuPVataoZSyZaMaZKKs7PbA

### 
GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MDI0NTI4fQ.fud-xwbiVHRZby2wJxNNWuPVataoZSyZaMaZKKs7PbA

### For my Reference
GET http://localhost:3000/tweets/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MDI0NTI4fQ.fud-xwbiVHRZby2wJxNNWuPVataoZSyZaMaZKKs7PbA

### For my Reference
GET  http://localhost:3000/userprofile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MDI0NTI4fQ.fud-xwbiVHRZby2wJxNNWuPVataoZSyZaMaZKKs7PbA